name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        kind: [static, shared]
        mode: [debug, release, check]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1.0.1
      with:
        xmake-version: latest
    - name: config
      run:  xmake config --demo=y --mode=${{ matrix.mode }} --kind=${{ matrix.kind }}
    - name: build
      run: xmake build -v -D
    - name: test [simple]
      run: xmake run demo_simple
    - name: test [epoll]
      run: xmake run demo_epoll
